language: python
python:
  - "3.6"
install:
  - pip3 install -r requirements.txt
jobs:
  include:
    - stage: check
      script:
        - flake8 .
        - isort -c
        - black --check .
    - state: test
      script:
        - echo "Everything ok!"