"""followers

Revision ID: 978923788e83
Revises: 9b7370685d4d
Create Date: 2020-01-15 16:30:46.453729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978923788e83'
down_revision = '9b7370685d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
